### ISSUE TITLE
Paste sharing

### ISSUE THREAD

**Issue by haggen** [haggen/localthreat#2]
1. Generate an unique ID for each paste
2. Append it to the URL
3. Save both ID and paste content into some back-end (Firebase?)
4. Save a history of pastes for current user (browser storage, cookies, etc.)
5. Load the paste content when visiting a URL with an existing ID

**Comment by Chnkr** [comment]
You could just B64 the pilot names and attach it to the URL, saves you on storage

**Comment by haggen** [comment]
@Chnkr I thought about it, but I had my doubts about length/friendliness of theURL. Might give it a try anyway. Thank you! :)
