### ISSUE TITLE
Broken zKill links

### ISSUE THREAD

**Issue by crossedxd** [haggen/localthreat#24]
Something changed recently on zKill's side of things that's unearthed a bit of an issue in the code here.  The links to zKill being generated by localthreat are generating errors because they're missing trailing slashes in the URLs.

I haven't been able to test it, but tweaking the getEntityURL code in entity.js should probably help fix the problem (the code below has the slashes added in):
```
const getEntityURL = (type, id) => {
  switch (type) {
    case "char":
      return `https://zkillboard.com/character/${id}/`;
    case "ally":
      return `https://zkillboard.com/alliance/${id}/`;
    case "corp":
      return `https://zkillboard.com/corporation/${id}/`;
    case "ship":
      return `https://zkillboard.com/character/${id[1]}/shipTypeID/${id[0]}/`;
  }
};
```

**Comment by haggen** [comment]
Fixed with #27
