### ISSUE TITLE
Not recognizing attempts to paste

### ISSUE THREAD

**Issue by tyrantrook** [haggen/localthreat#48]
Apologies if this is a known issue or something local to me, but about a week ago I became unable to paste into the page, even though I verified the clipboard held the pilot list. No-adblocker. Incognito mode doesn't work, either. Tried Chrome and Edge.

**Comment by jmcalmel** [comment]
I have the same issue.

I'm on MacOS 10.14.6 and have tried Safari and Firefox.

Last time I saw it working properly was November 7th in the morning.

No system update on my machine occurred since then.

**Comment by haggen** [comment]
Thank you both @tyrantrook and @jmcalmel for the report! 🍻

I'll look into it as soon as I can. Any more details you could provide? Like what happens when you `CTRL/CMD`+`V` on the page? Nothing? No errors on the console? What system @tyrantrook is on?

Thank you once again!

**Comment by tyrantrook** [comment]
Console:
index.tsx:13 POST https://api.localthreat.xyz/v1/reports net::ERR_ABORTED 500
(anonymous) @ index.tsx:13
Du @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
zu @ react-dom.production.min.js:261
(anonymous) @ react-dom.production.min.js:261
I @ scheduler.production.min.js:16
k.port1.onmessage @ scheduler.production.min.js:12

index.tsx:19 Uncaught (in promise) Error: Unhandled status 500
    at index.tsx:19
(anonymous) @ index.tsx:19
Promise.catch (async)
(anonymous) @ index.tsx:26
Du @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
zu @ react-dom.production.min.js:261
(anonymous) @ react-dom.production.min.js:261
I @ scheduler.production.min.js:16
k.port1.onmessage @ scheduler.production.min.js:12

I'm on Windows 10 pro, build 19041.572, if that's what you were asking.

Thanks for taking a look!

**Comment by haggen** [comment]
Thanks for the great reports guys. I've identified the culprit (something with the db connection pooling). I'm gonna link into it later today. For now a restart fixed the issue (until it happens again).

**Comment by tyrantrook** [comment]
Works for me now, thank you!
